apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: iavf-vfio
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/modprobe.d/vfio.conf
          mode: 0644
          overwrite: true
          contents:
            source: data:text/plain;charset=utf-8;base64,b3B0aW9ucyB2ZmlvLXBjaSBpZHM9ODA4NjoxODg5Cg==
        - path: /etc/modules-load.d/vfio-pci.conf
          mode: 0644
          contents:
            inline: vfio-pci
