apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-hugepages-1gb
  labels:
    machineconfiguration.openshift.io/role: master  # Targeting only worker (SNO) nodes
spec:
  kernelArguments:
    - "hugepagesz=1G"
    - "hugepages=8"  # Adjust this to your desired number of hugepages (e.g., 4 hugepages of 1GB each)
  nodeSelector:
    kubernetes.io/hostname: okd-sno
