apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: load-ptpkvm-module
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/modprobe.d/ptp_kvm-blacklist.conf
          mode: 0644
          overwrite: true
          contents:
            source: data:,
        - path: /etc/modules-load.d/ptp_kvm-load.conf
          mode: 0644
          overwrite: true
          contents:
            source: data:,ptp_kvm
