apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: cpu-profile
  annotations:
    kubeletconfig.experimental: |
      {"allowedUnsafeSysctls":["net.ipv4.ip_forward"]}
spec:
  additionalKernelArgs:
  - "kthread_cpus=0-3"   # Confines most kernel threads to reserved CPUs
  - "mitigations=off"    # WARNING: Disables CPU security mitigations!
  cpu:
    reserved: "0-3"
    isolated: "4-31"
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  globallyDisableIrqLoadBalancing: true
  realTimeKernel:
    enabled: true
  workloadHints:
    highPowerConsumption: false
    perPodPowerManagement: false
    realTime: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
