apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # This should be <= the size of the PV
  storageClassName: manual  # This must match the PV's storageClassName
