apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: srsran-performance
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=SRS tuned profile
      include=-provider-${f:exec:cat:/var/lib/ocp-tuned/provider},openshift

      [bootloader]
      #Command line arguments passed to the kernel at system boot time
      #Any changes here will only take effect after reboot.
      cmdline="nosoftlockup selinux=0 enforcing=0 nmi_watchdog=0 crashkernel=auto softlockup_panic=0 nosoftlockup audit=0 mce=off mitigations=off tsc=nowatchdog skew_tick=1"
      [cpu]
      energy_perf_bias=performance
      force_latency=cstate.id:1|99
      governor=performance
      min_perf_pct=100

      [sysctl]

      kernel.sched_rt_runtime_us=980000

      # Busy polling helps reduce latency in the network receive path
      # by allowing socket layer code to poll the receive queue of a
      # network device, and disabling network interrupts.
      # busy_read value greater than 0 enables busy polling. Recommended
      # net.core.busy_read value is 50.
      # busy_poll value greater than 0 enables polling globally.
      # Recommended net.core.busy_poll value is 50
      net.core.busy_poll=50
      net.core.busy_read=50

      # TCP fast open reduces network latency by enabling data exchange
      # during the sender's initial TCP SYN. The value 3 enables fast open
      # on client and server connections.
      net.ipv4.tcp_fastopen=3

      # If a workload mostly uses anonymous memory and it hits this limit,
      # the entire working set is buffered for I/O, and any more write buffering
      # would require swapping, so it's time to throttle writes
      # until I/O can catch up.  Workloads that mostly use file mappings
      # may be able to use even higher values.
      #
      # The generator of dirty data starts writeback at this percentage
      # (system default is 20%)
      vm.dirty_ratio=10

      # Start background writeback (via writeback threads) at this percentage
      # (system default is 10%)
      vm.dirty_background_ratio=3

      # The swappiness parameter controls the tendency of the kernel to move
      # processes out of physical memory and onto the swap disk.
      # 0 tells the kernel to avoid swapping processes out of physical memory
      # for as long as possible
      # 100 tells the kernel to aggressively swap processes out of physical memory
      # and move them to swap cache
      vm.swappiness=10

      [vm]
      transparent_hugepages=never

    name: srsran-performance
  recommend:
  - profile: srsran-performance
    priority: 10
    match:
    - label: node-role.kubernetes.io/master
