# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured 
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync 
# is not defined and the default is used. 

gnb_du_id: 1

cu_cp:
  inactivity_timer: 7200
  amf:
    addr: ${AMF_ADDR}               # The address or hostname of the AMF.
    bind_addr: ${AMF_BIND_ADDR}         # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas:                                    # Configure the TA associated with the CU-CP
      - tac: 1
        plmn_list:
          -
            plmn: "00101"
            tai_slice_support_list:
              -
                sst: 1

cell_cfg:
  dl_arfcn: 666624                  # ARFCN of the downlink carrier (center frequency).
  band: 77                           # The NR band.
  channel_bandwidth_MHz: 40          # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                   # Subcarrier spacing in kHz used for data.
  plmn: "00101"                   # PLMN broadcasted by the gNB.
  tac: 1                            # Tracking area code (needs to match the core configuration).
  nof_antennas_dl: 2                    # Optional UINT (1). Sets the number of antennas for downlink transmission. Supported: [1, 2, 4].
  nof_antennas_ul: 2                    # Optional UINT (1). Sets the number of antennas for uplink transmission. Supported: [1, 2, 4].  
  prach:
    prach_config_index: 159           # Sets PRACH config to match what is expected by srsUE      
    prach_root_sequence_index: 1
    prach_frequency_start: 0
    zero_correlation_zone: 0
    ra_resp_window: 10
    # nof_cb_preambles_per_ssb: 15
  pusch:
    dmrs_additional_position: 2
    msg3_delta_preamble: 2
    p0_nominal_with_grant: -100
  pucch:
    p0_nominal: -96
  pdcch:
    common:
      coreset0_index: 11                           # Optional INT. Sets the CORESET 0 index. Supported: [0 - 15].
      ss0_index: 0                              # Optional UINT (0). Sets the SearchSpace#0 index. Supported: [0 - 15].
    dedicated:
      coreset1_rb_start: 0                      # Optional INT (0). Sets the starting common resource block (CRB) number for CORESET 1, relative to CRB0. Supported: [0 - 275].
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_symbols: 6                                               # Number of Downlink symbols at the beginning of the slot following full Downlink slots. OAI Config: nrofDownlinkSymbols
    nof_ul_symbols: 4                                               # Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. OAI Config: nrofUplinkSymbols
    nof_dl_slots: 7                                                 # Number of consecutive full Downlink slots.  OAI Config: nrofDownlinkSlots
    nof_ul_slots: 2                                                 # Number of consecutive full Uplink slots.  OAI Config: nrofUplinkSlots
  ssb:
    ssb_period: 20     
    ssb_block_power_dbm: 0
  ul_common:
    p_max: 23

  slicing:
  {{- range .Values.config.slicing }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}


ru_ofh:
  ru_bandwidth_MHz: 40
  t1a_max_cp_dl: 336
  t1a_min_cp_dl: 285
  t1a_max_cp_ul: 211
  t1a_min_cp_ul: 160
  t1a_max_up: 345
  t1a_min_up: 294
  ta4_max: 331
  ta4_min: 50
  # ignore_ecpri_seq_id: true            # Optional BOOLEAN (false). Sets whether or not to ignore eCPRI sequence ID field value. Supported [false, true].
  ignore_ecpri_payload_size: true      # Optional BOOLEAN (false). Sets whether or not to ignore eCPRI payload size field value. Supported [false, true].
  is_prach_cp_enabled: true           # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                 # Uplink compression method.
  compr_bitwidth_ul: 9                 # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                 # Downlink compression method.
  compr_bitwidth_dl: 9                 # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp              # PRACH compression method.
  compr_bitwidth_prach: 9              # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: true     # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: true     # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 7                   # IQ samples scaling factor applied before compression, should be a positive value smaller than 10. (5!)
  cells:
    - network_interface: 0000:01:00.0     # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 1c:a0:ef:87:68:b6   # RU MAC address.
      du_mac_addr: 72:0e:9b:5f:81:df   # DU MAC address.
      vlan_tag_cp: 10                   # VLAN tag value for CP.
      vlan_tag_up: 10                   # VLAN tag value for UP.
      prach_port_id: [8, 9]            # PRACH eAxC port value.
      dl_port_id: [0, 1]         # Downlink eAxC port values.
      ul_port_id: [0, 1]              # Uplink eAxC port values.


e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: ${E2_ADDR}                 # RIC IP address
  bind_addr: ${AMF_BIND_ADDR}
  port: 36421                       # RIC port

metrics:
  rlc_report_period: 1000           # Set reporting period to 1s
  enable_json_metrics: true       # Enable reporting metrics in JSON format
  addr: grafana-srsran-metrics-server              # Metrics-server IP
  port: 55555                     # Metrics-server Port  
  autostart_stdout_metrics: true

hal:
   eal_args: "--lcores (0-1)@(4-7) -a 0000:01:00.0"

expert_execution:
  affinities:
    low_priority_cpus: 13,14
    ru_timing_cpu: 8
    ofh: 18,19
  cell_affinities:
    -
       l1_dl_cpus: 9,10
       l1_ul_cpus: 11,12
       l2_cell_cpus: 16
       ru_cpus: 15


log:
  filename: stdout         # Path of the log file.
  all_level: warning                   # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: ./gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: ./gnb_ngap.pcap # Path where the NGAP PCAP is stored.
