# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured 
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync 
# is not defined and the default is used. 

gnb_du_id: 1

cu_cp:
  inactivity_timer: 7200
  amf:
    addr: ${AMF_ADDR}               # The address or hostname of the AMF.
    bind_addr: ${AMF_BIND_ADDR}         # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas:                                    # Configure the TA associated with the CU-CP
      - tac: 1
        plmn_list:
          -
            plmn: "99970"
            tai_slice_support_list:
              -
                sst: 1
                sd: 0x111111

# ru_sdr:
#   device_driver: {{ .Values.config.ru_sdr.device_driver }}                                               # The RF driver name.
#   device_args: {{ .Values.config.ru_sdr.device_args }}     # Optionally pass arguments to the selected RF driver.
#   srate: {{ .Values.config.ru_sdr.srate }}
#   tx_gain: {{ .Values.config.ru_sdr.tx_gain }}                     # Transmit gain of the RF might need to adjusted to the given situation.
#   rx_gain: {{ .Values.config.ru_sdr.rx_gain }}                       # Receive gain of the RF might need to adjusted to the given situation.

cell_cfg:
  dl_arfcn: 666624                  # ARFCN of the downlink carrier (center frequency).
  band: 77                           # The NR band.
  channel_bandwidth_MHz: 40          # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 30                   # Subcarrier spacing in kHz used for data.
  plmn: {{ .Values.config.cell_cfg.plmn }}                   # PLMN broadcasted by the gNB.
  tac: {{ .Values.config.cell_cfg.tac }}                            # Tracking area code (needs to match the core configuration).
  nof_antennas_dl: 2                    # Optional UINT (1). Sets the number of antennas for downlink transmission. Supported: [1, 2, 4].
  nof_antennas_ul: 2                    # Optional UINT (1). Sets the number of antennas for uplink transmission. Supported: [1, 2, 4].  
  prach:
    prach_config_index: 159           # Sets PRACH config to match what is expected by srsUE      
    prach_root_sequence_index: 1
    prach_frequency_start: 0
    zero_correlation_zone: 0
  pusch:
    dmrs_additional_position: 2
    msg3_delta_preamble: 2
  pucch:
    p0_nominal: -96
  pdcch:
    common:
      coreset0_index: 11
      ss0_index: 0
  tdd_ul_dl_cfg:
    dl_ul_tx_period: 10
    nof_dl_symbols: 6                                               # Number of Downlink symbols at the beginning of the slot following full Downlink slots. OAI Config: nrofDownlinkSymbols
    nof_ul_symbols: 4                                               # Number of Uplink symbols at the end of the slot preceding the first full Uplink slot. OAI Config: nrofUplinkSymbols
    nof_dl_slots: 7                                                 # Number of consecutive full Downlink slots.  OAI Config: nrofDownlinkSlots
    nof_ul_slots: 2                                                 # Number of consecutive full Uplink slots.  OAI Config: nrofUplinkSlots
  ssb:
    ssb_period: 20     
  ul_common:
    p_max: 23

  slicing:
  {{- range .Values.config.slicing }}
    - {{- toYaml . | nindent 6 }}
    {{- end }}


ru_ofh:
  t1a_max_cp_dl: 470
  t1a_min_cp_dl: 285
  t1a_max_cp_ul: 429
  t1a_min_cp_ul: 285
  t1a_max_up: 350
  t1a_min_up: 125
  ta4_max: 180
  ta4_min: 110
  is_prach_cp_enabled: true           # Configures if Control-Plane messages should be used to receive PRACH messages.
  compr_method_ul: bfp                 # Uplink compression method.
  compr_bitwidth_ul: 9                 # Uplink IQ samples bitwidth after compression.
  compr_method_dl: bfp                 # Downlink compression method.
  compr_bitwidth_dl: 9                 # Downlink IQ samples bitwidth after compression.
  compr_method_prach: bfp              # PRACH compression method.
  compr_bitwidth_prach: 9              # PRACH IQ samples bitwidth after compression.
  enable_ul_static_compr_hdr: false     # Configures if the compression header is present for uplink User-Plane messages (false) or not present (true).
  enable_dl_static_compr_hdr: false     # Configures if the compression header is present for downlink User-Plane messages (false) or not present (true).
  iq_scaling: 1                       # IQ samples scaling factor applied before compression, should be a positive value smaller than 10.
  cells:
    - network_interface: 0000:01:00.0     # Ethernet interface name used to communicate with the RU.
      ru_mac_addr: 1c:a0:ef:87:68:b6   # RU MAC address.
      du_mac_addr: 72:0e:9b:5f:81:df   # DU MAC address.
      # vlan_tag_cp: 10                   # VLAN tag value for CP.
      # vlan_tag_up: 10                   # VLAN tag value for UP.
      prach_port_id: [8, 9]            # PRACH eAxC port value.
      dl_port_id: [0, 1]         # Downlink eAxC port values.
      ul_port_id: [0, 1]              # Uplink eAxC port values.


# e2:
#   enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
#   e2sm_kpm_enabled: true            # Enable KPM service module
#   e2sm_rc_enabled: false             # Enable RC service module
#   addr: ${E2_ADDR}                 # RIC IP address
#   bind_addr: ${AMF_BIND_ADDR}
#   port: 36421                       # RIC port

metrics:
  rlc_report_period: 1000           # Set reporting period to 1s
  enable_json_metrics: true       # Enable reporting metrics in JSON format
  addr: grafana-srsran-metrics-server              # Metrics-server IP
  port: 55555                     # Metrics-server Port  

hal:
   eal_args: "--lcores (0-1)@(28-31) -a 0000:01:00.0"

expert_execution:
  affinities:
    isolated_cpus: "28-31" # Core 28, 29, 30, 31 are isolated
  cell_affinities:
    -
      l1_dl_cpus: "28,29"  # DL threads on cores 28 and 29
      l1_ul_cpus: "30,31"  # UL threads on cores 30 and 31
      ru_cpus: "28,29" # RU threads on cores 28 and 29

log:
  filename: stdout         # Path of the log file.
  all_level: info                   # Logging level applied to all layers.

pcap:
  mac_enable: false                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: ./gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: false                # Set to true to enable NGAP PCAPs.
  ngap_filename: ./gnb_ngap.pcap # Path where the NGAP PCAP is stored.
