apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-monitoring
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  monitoring.py: |
{{ tpl (.Files.Get "resources/monitoring.py") . | indent 4 }}
