apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-entrypoint
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  k8s-entrypoint.sh: |
    {{- /* Process the script, passing the top-level context '$' */ -}}
    {{- tpl (.Files.Get "resources/k8s-entrypoint.sh") $ | nindent 4 }}
