apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-iperf3
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  iperf3-test.sh: |
{{ tpl (.Files.Get "resources/iperf3-test.sh") . | indent 4 }}
