apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
      annotations:
        cpu-quota.crio.io: "disable"
        cpu-load-balancing.crio.io: "disable"
        config-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "open5gs.upf.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      serviceAccountName: {{ include "open5gs.upf.serviceAccountName" . }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      # yamllint disable rule:indentation
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      # yamllint enable rule:indentation
      {{- end }}
      initContainers:
        - name: tun-create
          image: {{ template "open5gs.upf.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - "/bin/bash" 
            - "-c"
            - "/k8s-entrypoint.sh"
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              memory: 16Gi
              cpu: 2
            limits:
              memory: 16Gi
              cpu: 2
          volumeMounts:
            - name: entrypoint
              mountPath:  /k8s-entrypoint.sh
              subPath: k8s-entrypoint.sh
        {{- if .Values.initContainers }} 
        {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "common.names.fullname" . }}
          image: {{ template "open5gs.upf.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/sh
            - -c
            - |
              curl -kL https://github.com/userdocs/iperf3-static/releases/download/3.18/iperf3-amd64 -o /usr/bin/iperf3 &&
              curl -kL https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64 -o /usr/bin/jq &&
              chmod +x /usr/bin/jq &&
              stdbuf -o0 iperf3 -s &
              taskset -pc 22 $!  # core 30
          
              stdbuf -o0 iperf3 -s -p 5202 &
              taskset -pc 23 $!  # core 31
          
              stdbuf -o0 iperf3 -s -p 5203 &
              taskset -pc 24 $!  # core 62
          
              stdbuf -o0 iperf3 -s -p 5204 &
              taskset -pc 25 $!  # core 63
          
              stdbuf -o0 iperf3 -s -p 5205 &
              taskset -pc 26 $!  # core 64
              open5gs-upfd
          {{- end }}
          {{- if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.extraEnvVars }}
          env:
            {{- include "common.tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - name: pfcp
              containerPort: {{ .Values.containerPorts.pfcp }}
              protocol: UDP
            - name: gtpu
              containerPort: {{ .Values.containerPorts.gtpu }}
              protocol: UDP
            - name: metrics
              containerPort: {{ .Values.containerPorts.metrics }}
          {{- if .Values.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customStartupProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customLivenessProbe "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.customReadinessProbe "context" $) | nindent 12 }}
          {{- end }}
          resources:
            requests:
              memory: 16Gi
              cpu: 2
            limits:
              memory: 16Gi
              cpu: 2
          volumeMounts:
            - name: local-storage
              mountPath: /mnt/data
            - name: config
              mountPath:  /opt/open5gs/etc/open5gs/upf.yaml
              subPath: "upf.yaml"
            - name: iperf3-test
              mountPath: /iperf3-test.sh
              subPath: "iperf3-test.sh"
            - name: iperf3-simple
              mountPath: /downclock-test.sh
              subPath: "downclock-test.sh"
            {{- if .Values.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.sidecars "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.start.iperf3 }}
        - name: iperf3
          image: "docker.io/networkstatic/iperf3:latest"
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
              drop:
                - ALL
          command:
            - /bin/sh
            - -c
            - |
              stdbuf -o0 iperf3 -s &
              taskset -pc 22 $!  # core 30
          
              stdbuf -o0 iperf3 -s -p 5202 &
              taskset -pc 23 $!  # core 31
          
              stdbuf -o0 iperf3 -s -p 5203 &
              taskset -pc 24 $!  # core 62
          
              stdbuf -o0 iperf3 -s -p 5204 &
              taskset -pc 25 $!  # core 63
          
              stdbuf -o0 iperf3 -s -p 5205 &
              taskset -pc 26 $!  # core 64
          
              wait

          {{- else }}
          command:
            - /bin/sleep
            - infinity
        {{- end }}      
      runtimeClassName: performance-srsran-profile
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-pvc
        - name: config
          configMap:
            name: {{ include "common.names.fullname" . }}
        - name: iperf3-test
          configMap:
            name: {{ include "common.names.fullname" . }}-iperf3
            defaultMode: 0777            
        - name: iperf3-simple
          configMap:
            name: {{ include "common.names.fullname" . }}-iperf3-simple
            defaultMode: 0777            
        - name: entrypoint
          configMap:
            name: {{ include "common.names.fullname" . }}-entrypoint
            defaultMode: 0777
        {{- if .Values.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
