apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-metrics
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  start-metrics.sh: |
{{ tpl (.Files.Get "resources/start-metrics.sh") . | indent 4 }}
