apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-vpp
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  startup.conf: |
{{ tpl (.Files.Get "resources/startup.conf") . | indent 4 }}
