dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-dbctl
    tag: 0.10.3
    pullPolicy: IfNotPresent
  initCommands: 
  - open5gs-dbctl add_ue_with_slice 001010000000001 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant1 1 000001
  - open5gs-dbctl add_ue_with_slice 001010000000002 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant1 1 000001
  - open5gs-dbctl add_ue_with_slice 001010000000003 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant2 1 000002
  - open5gs-dbctl add_ue_with_slice 001010000000004 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant2 1 000002
  - open5gs-dbctl add_ue_with_slice 001010000000005 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant3 1 000003
  - open5gs-dbctl add_ue_with_slice 001010000000006 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant3 1 000003
  - open5gs-dbctl add_ue_with_slice 001010000000007 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant4 1 000004
  - open5gs-dbctl add_ue_with_slice 001010000000008 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant4 1 000004
  - open5gs-dbctl add_ue_with_slice 001010000000009 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant5 1 000005
  - open5gs-dbctl add_ue_with_slice 001010000000010 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant5 1 000005
  - open5gs-dbctl add_ue_with_slice 001010000000011 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 tenant6 1 000006
# Common
mongodb:
  enabled: true
  persistence:
    enabled: false
  auth:
    enabled: false
smf:
  enabled: true
  config:
    scp:
      enabled: true
    pcrf:
      enabled: false
    frdi:
      hostname: ""  # if empty default is autogenerated open5gs svc fullname
      port: 3868
  dnsList:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
  subnetList:
    - subnet: 10.45.0.0/24
      gateway: 10.45.0.1
      dnn: oai
    - subnet: 10.45.1.0/24
      gateway: 10.45.1.1
      dnn: tenant1
    - subnet: 10.45.2.0/24
      gateway: 10.45.2.1
      dnn: tenant2
    - subnet: 10.45.3.0/24
      gateway: 10.45.3.1
      dnn: tenant3
    - subnet: 10.45.4.0/24
      gateway: 10.45.4.1
      dnn: tenant4
    - subnet: 10.45.5.0/24
      gateway: 10.45.5.1
      dnn: tenant5
    - subnet: 10.45.6.0/24
      gateway: 10.45.6.1
      dnn: tenant6
  mtu: 1400
upf:
  enabled: true
  logLevel: info
  gtpu:
    dev: ""
    advertise: ""
subnetList:
  - subnet: 10.45.0.0/24
    gateway: 10.45.0.1
    dnn: oai
    dev: ogstun
    mask: 24
    createDev: true
    enableNAT: true
  - subnet: 10.45.1.0/24
    gateway: 10.45.1.1
    dnn: tenant1
    dev: ogstun
    mask: 24
    createDev: false
    enableNAT: true
  - subnet: 10.45.2.0/24
    gateway: 10.45.2.1
    dnn: tenant2
    dev: ogstun
    mask: 24
    createDev: false
    enableNAT: true
  - subnet: 10.45.3.0/24
    gateway: 10.45.3.1
    dnn: tenant3
    dev: ogstun
    mask: 24
    createDev: false
    enableNAT: true
  - subnet: 10.45.4.0/24
    gateway: 10.45.4.1
    dnn: tenant4
    dev: ogstun
    mask: 24
    createDev: false
    enableNAT: true
  - subnet: 10.45.5.0/24
    gateway: 10.45.5.1
    dnn: tenant5
    dev: ogstun
    mask: 24
    createDev: false
    enableNAT: true
  - subnet: 10.45.6.0/24
    gateway: 10.45.6.1
    dnn: tenant6
    dev: ogstun
    mask: 24
    createDev: false
    enableNAT: true
webui:
  ingress:
    hostname: open5gs.sno.oran.lab
  enabled: true

# 4G
hss:
  enabled: false
  mongodb:
    enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false

# 5G
amf:
  services:
    sbi:
      clusterIP: None
  enabled: true
  config:
    guamiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        s_nssai:
          - sst: 1
            sd: "0x000001"   # Tenant 1
          - sst: 1
            sd: "0x000002"   # Tenant 2
          - sst: 1
            sd: "0x000003"   # Tenant 3
          - sst: 1
            sd: "0x000004"   # Tenant 4
          - sst: 1
            sd: "0x000005"   # Tenant 5
          - sst: 1
            sd: "0x000006"   # Tenant 6
  networkName: Gradiant

ausf:
  enabled: true
bsf:
  enabled: true
nrf:
  enabled: true
  config:
    servingList:
      - plmn_id:
          mcc: 001
          mnc: 01
nssf:
  enabled: true
  config:
    nsiList:
      - nrf:
          hostname: "open5gs-nrf-sbi"  # Default if empty
          port: 7777
        sst: 1
        sd: "0x000001"   # Tenant 1
      - nrf:
          hostname: "open5gs-nrf-sbi"  # Default if empty
          port: 7777
        sst: 1
        sd: "0x000002"   # Tenant 2
      - nrf:
          hostname: "open5gs-nrf-sbi"  # Default if empty
          port: 7777
        sst: 1
        sd: "0x000003"   # Tenant 3
      - nrf:
          hostname: "open5gs-nrf-sbi"  # Default if empty
          port: 7777
        sst: 1
        sd: "0x000004"   # Tenant 4
      - nrf:
          hostname: "open5gs-nrf-sbi"  # Default if empty
          port: 7777
        sst: 1
        sd: "0x000005"   # Tenant 5
      - nrf:
          hostname: "open5gs-nrf-sbi"  # Default if empty
          port: 7777
        sst: 1
        sd: "0x000006"   # Tenant 6

pcf:
  enabled: true
  mongodb:
    enabled: false
scp:
  enabled: true
  mongodb:
    enabled: false
udm:
  enabled: true
udr:
  enabled: true
  mongodb:
    enabled: false
