dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
  enabled: true
  image:
    registry: docker.io
    repository: gradiant/open5gs-dbctl
    tag: 0.10.3
    pullPolicy: IfNotPresent
  initCommands: 
  - open5gs-dbctl add_ue_with_apn 001010000000001 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 oai 1
  - open5gs-dbctl add_ue_with_apn 001010000000002 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 oai 1
  - open5gs-dbctl add_ue_with_apn 001010000000003 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 oai 1
  - open5gs-dbctl add_ue_with_apn 001010000000004 fec86ba6eb707ed08905757b1bb44b8f C42449363BBAD02B66D16BC975D77CC1 oai 1
# Common
mongodb:
  enabled: true
  persistence:
    enabled: false
  auth:
    enabled: false
smf:
  enabled: true
  config:
    scp:
      enabled: true
    pcrf:
      enabled: false
upf:
  enabled: true
webui:
  ingress:
    hostname: open5gs.sno.oran.lab
  enabled: true

# 4G
hss:
  enabled: false
  mongodb:
    enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false

# 5G
amf:
  services:
    sbi:
      clusterIP: None
  enabled: true
  config:
    guamiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        amf_id:
          region: 2
          set: 1
    taiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        tac: [1]
    plmnList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        s_nssai:
          - sst: 1
ausf:
  enabled: true
bsf:
  enabled: true
nrf:
  enabled: true
nssf:
  enabled: true
  config:
    nsiList:
      - nrf:
          hostname: ""  # if empty default is autogenerated open5gs svc fullname
          port: 7777
        sst: 1
pcf:
  enabled: true
  mongodb:
    enabled: false
scp:
  enabled: true
  mongodb:
    enabled: false
udm:
  enabled: true
udr:
  enabled: true
  mongodb:
    enabled: false
