# This example configuration outlines how to configure the srsRAN Project gNB to create a single TDD cell
# transmitting in band 78, with 20 MHz bandwidth and 30 kHz sub-carrier-spacing. A USRP B200 is configured 
# as the RF frontend using split 8. Note in this example an external clock source is not used, so the sync 
# is not defined and the default is used. 


cu_cp:
  f1ap:
    bind_addr: 10.10.1.1                   # Optional TEXT (127.0.0.1). Sets the F1-c bind address. 
    procedure_timeout: 1000                  # Optional INT (1000). Sets the time the F1AP waits for a DU response in milliseconds.
  inactivity_timer: 7200
  amf:
    addr: ${AMF_ADDR}               # The address or hostname of the AMF.
    bind_addr: ${AMF_BIND_ADDR}         # A local IP that the gNB binds to for traffic from the AMF.
    supported_tracking_areas:                                    # Configure the TA associated with the CU-CP
      - tac: 1
        plmn_list:
          -
            plmn: "00101"
            tai_slice_support_list:
              -
                sst: 1

cu_up: 
  gtpu_queue_size: 2048                # Optional INT (2048). Sets the GTP-U queue size, in PDUs.
  gtpu_reordering_timer: 0             # Optional INT (0). Sets the GTP-U RX reordering timer (in milliseconds).
  warn_on_drop: false                  # Optional BOOLEAN (false). Enables the option to log a warning for dropped packets in GTP-U and PDCP due to full queues. Supported: [false, true].

  f1u:
      socket:                               # Define UDP/IP socket(s) for F1-U interface.
        -                                     # Socket 1
          bind_addr: 10.10.1.1                 # Required TEXT. Sets the address that the F1-U socket will bind to.
          udp:
            max_rx_msgs: 256                        # Optional UINT (256). Sets the maximum packets read from the socket in a single syscall.
            pool_threshold: 0.9                     # Optional FLOAT (0.9). Sets the pool occupancy threshold, after which packets are dropped. Supported [0 - 1.0]. 
  

e2:
  enable_cu_cp_e2: true                # Optional BOOLEAN (false). Enables the CU-CP E2 agent. Supported: [false, true]. 
  enable_cu_up_e2: true                # Optional BOOLEAN (false). Enables the CU-UP E2 agent. Supported: [false, true]. 
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: ${E2_ADDR}                 # RIC IP address
  bind_addr: ${AMF_BIND_ADDR}
  port: 36421                       # RIC port

metrics:
  rlc_report_period: 1000           # Set reporting period to 1s
  enable_json_metrics: true       # Enable reporting metrics in JSON format
  addr: grafana-srsran-metrics-server             # Metrics-server IP
  port: 55555                     # Metrics-server Port  
  autostart_stdout_metrics: true


expert_execution:
  affinities:
    low_priority_cpus: 13
  #   low_priority_cpus:                    # Optional TEXT. Sets the CPU core(s) assigned to low priority tasks. Supported: [1, 2, 3 , ..., N].
  #   low_priority_pinning:                 # Optional TEXT. Sets the policy used for assigning CPU cores to low priority tasks.   
  # threads:
  #   non_rt:
  #     nof_non_rt_threads: 4                   # Optional UINT (4). Sets the number of non real time threads for processing of CP and UP data in upper layers.
  #     non_rt_task_queue_size: 2048            # Optional UINT (2048). Sets the non real time task worker queue size. 


log:
  filename: stdout         # Path of the log file.
  all_level: warning                   # Logging level applied to all layers.
